# These are supported funding model platforms

github: [saarock]
patreon: saarock
open_collective: saarock
ko_fi: saarock
tidelift: bun/npm/yarn
community_bridge: notty
liberapay: saarock
issuehunt: saarock
lfx_crowdfunding: notty
polar: saarock
buy_me_a_coffee: saarock
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
